### ISSUE TITLE
Doesn't work with Next.js

### ISSUE THREAD

**Issue by anakis** [Nozbe/zacs#12]
First of all, your lib is awesome!

Can you please help me to configure a workable example with next.js? I followed your steps and used the example provided by nextjs to work [with a custom babel config](https://github.com/zeit/next.js/tree/canary/examples/with-custom-babel-config) and receives the following error: zacs.viewmethod called directly (not transpiled). Your Babel file is probably misconfigured or you have a syntax error

**Comment by radex** [comment]
show us the transpiled JS code
