### ISSUE TITLE
Add more elements

### ISSUE THREAD

**Issue by leiteszeke** [Nozbe/zacs#6]
Hi. 

I'm generating an example project using the library, but I could see that Image is not implemented for React Native, it's for any particular reason? 

I read the source code and check to add it, but how do you build the source code I could not found some webpack configuration or anything else?

Thanks

**Comment by radex** [comment]
@leiteszeke what do you mena "Image is not implemented for react native"?

> I read the source code and check to add it, but how do you build the source code I could not found some webpack configuration or anything else?

i don't understand the question

**Comment by leiteszeke** [comment]
Actually the library only support View and Text elements right? And i'm trying to implement an Image Element, i check in the source code and aparently Image is not implemented but could be, it's this correct?

**Comment by radex** [comment]
@leiteszeke no, that's not right. You can style any component — have you read the docs? https://github.com/Nozbe/zacs

**Comment by leiteszeke** [comment]
@radex Yes, but apparently I misunderstood the implementation, I was looking to use a method like zacs.image but well, I solve it directly using styled components or a component outside the library. Thank you.
